name: Integration test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jpnock/langproc-env/langproc-env:v1.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        id: test
        timeout-minutes: 1
        run: |
          ./test.sh

      - name: Perm issue fix
        if: success() || failure()
        run: git config --global --add safe.directory /__w/langproc-env/langproc-env

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: bin/junit_results.xml
          reporter: java-junit
          fail-on-error: false
